### ISSUE TITLE
Internal error when using & nested in a pattern

### ISSUE THREAD

**Issue by mbravenboer** [RelationalAI-oss/Rematch.jl#1]
Writing something like this:
`Foo(Bar(e, xs, as1) & b, [], as2)`

Results in:
`ERROR: MethodError: no method matching assert_num_fields(::Base.#&, ::Int64)`

**Comment by jamii** [comment]
Hmmm. Maybe I should explicitly catch infix operators - they're never going to be valid struct names.

**Comment by jamii** [comment]
On master:

```
julia> x = 1
1

julia> @match (a && 1) = x
1

julia> @match (a & 1) = x
1

julia> @match (a + 1) = x
ERROR: AssertionError: Pattern a + 1 looks like a struct pattern but + is probably not a struct type.
```

**Comment by mbravenboer** [comment]
Thanks, looks great
