### ISSUE TITLE
Named matching of struct patterns using keyword arguments

### ISSUE THREAD

**Issue by sjoelund** [RelationalAI-oss/Rematch.jl#3]
I would like to perform matching based on the name of a field (because my structs have a very long list of field names and matching the correct name+pattern in much less error-prone especially if a field is added or removed from a large struct). Consider a small example below:

```jl
struct A
  a::Int
  b::Int
  c::Int
end

f(a) = @match a begin
  A(_,1,_) => 1
  A(b=2) => 1
end
```

I believe this should be possible with something like `getfield(a, :b) == 2` at runtime; possibly with a check to avoid errors.

**Comment by mbravenboer** [comment]
Just to confirm, this seems like a useful feature to me and also feasible to implement in the current macro implementation of Rematch.

**Comment by sjoelund** [comment]
Yes, it's possible and I also implemented it along with some features that probably shouldn't go into this package. I'm planning to automatically translate coffee in the MetaModelica language to Julia and introduced the matchcontinue construct (try next pattern on exception) and needed syntax for immutable lists. The code is at:
https://github.com/sjoelund/MetaModelica.jl/blob/master/src/matchcontinue.jl

There is some concern taken to optimize away assertions at compile-time although Julia couldn't quite remove all of them. I didn't have time to fully finish my work before the semester started and I got swamped with teaching.

**Comment by raileywild** [comment]
@sjoelund I've picked up this task and would like to incorporate your solution. Are you willing to assign the copyright to RelationalAI? Thanks!

**Comment by sjoelund** [comment]
> Are you willing to assign the copyright to RelationalAI?

I hereby give you a license to incorporate the [code in question](https://github.com/sjoelund/MetaModelica.jl/blob/45690eeb67e0bf6ccabc9f089b0fb72ade7a5b78/src/matchcontinue.jl) as you please, including removing the OSMC copyright notice and making the derived work the copyright of RelationalAI.

**Comment by raileywild** [comment]
Thanks @sjoelund !
